### ISSUE TITLE
An Error in the latest version

### ISSUE THREAD

**Issue by xiaotian1339** [cutelua/mtg-dist#11]
Verifying archive integrity...  100%   All good.
Uncompressing MTGDist [refs/tags/0.1.4][build 2021-07-20]  100%
==================================================
> Input service PORT, or press Enter to use a random port

> Input a domain for FakeTLS, or press Enter to use "hostupdate.vmware.com"
bing.com
==================================================
> Using: PORT: 23790, FakeTLS DOMAIN : bing.com
==================================================
./setup.sh: line 143: /usr/local/bin/mtg: No such file or directory

Error：
./setup.sh: line 143: /usr/local/bin/mtg: No such file or directory

**Comment by cutelua** [comment]
yes, it's a bug, fixed in v0.1.5
