### ISSUE TITLE
The 0.1.4 version has an error

### ISSUE THREAD

**Issue by xjl456852** [cutelua/mtg-dist#12]
I installed mtg by the command, encountered an error.
The error message was as follows:
/setup.sh: line 143: /usr/local/bin/mtg: No such file or directory

**Comment by SummerAfternoon** [comment]
./setup.sh: line 143: /usr/local/bin/mtg: No such file or directory

出错了😁😁😁

**Comment by JS-mark** [comment]
same error

**Comment by cutelua** [comment]
yes, it's a bug, fixed in v0.1.5
