### ISSUE TITLE
Use the installation command: (bash <(wget -qO- https://git.io/mtg.sh)) after that there is no response

### ISSUE THREAD

**Issue by xiaotian1339** [cutelua/mtg-dist#13]
Use the installation command: (bash <(wget -qO- https://git.io/mtg.sh)) after that there is no response.

**Comment by cutelua** [comment]
keep waiting until there's some error message.
Mostly it's just network being slow, for there's several redirect to git.io links

**Comment by xiaotian1339** [comment]
Sorry to ask again. After I entered the command, he directly quit. As shown in the figure, I waited for a while, but there was no feedback and no error log output. I executed the uninstall command, but still the same result. 


![image](https://user-images.githubusercontent.com/81060593/130312062-a2c1015f-f608-4ba6-92ff-509a1dd01d55.png)

**Comment by xiaotian1339** [comment]
Sorry to ask again. After I entered the command, he directly quit. As shown in the figure, I waited for a while, but there was no feedback and no error log output. I executed the uninstall command, but still the same result. 
![image](https://user-images.githubusercontent.com/81060593/130312129-5663cb38-6ee8-4148-a84f-ccc1b8814dc3.png)

**Comment by cutelua** [comment]
I think there must be some problem with the network.
You may just run `wget O- https://git.io/mtg.sh` to see what  it gets.

Maybe you should try the offline install method, as described in the front page
