### ISSUE TITLE
Permission denied Error

### ISSUE THREAD

**Issue by lynkco01** [cutelua/mtg-dist#9]
root@localhost:~# bash <(wget -qO- https://git.io/mtg.sh)
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Bullshit-free MTPROTO proxy Bin package [build 2021-07-19]  100%
/tmp/tmp.0gumyTDRyV/mtg.bin: line 655: ./setup.sh: Permission denied

**Comment by cutelua** [comment]
fixed in the latest ver
